name: Download Yuque Knowledge Base

on:
  push:
    branches: [ main ]

jobs:
  download:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install yuque-dl
      run: npm install -g yuque-dl

    - name: Download Yuque content
      run: |
        yuque-dl "${{ vars.YUQUE_URL }}" -t "${{ secrets.YUQUE_TOKEN }}" -d ./download --incremental
      env:
        YUQUE_URL: ${{ vars.YUQUE_URL }}
        YUQUE_TOKEN: ${{ secrets.YUQUE_TOKEN }}

    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add ./download
        git diff --staged --quiet || git commit -m "Update Yuque knowledge base [skip ci]"
        git push
